---
- hosts: leafs
  connection: local
  gather_facts: no
  
  vars_files:
    - group_vars/decommission.yml
  
  tasks:    
    - name: Check decommission list
      debug:
        msg: "Decommissioning {{ decommission_vlans | length }} VLANs"
      when: decommission_vlans | length > 0