---
- hosts: leafs
  connection: local
  gather_facts: no

  tasks:
  - name: Configure Customer Vrf
    eos_config:
      src: customer_vrf.j2

  - name: Configure Customer Vlans
    eos_config:
      src: vlans.j2

  - name: Configure Customer Svis
    eos_config:
      src: customer_svi.j2

  - name: Configure Customer Vxlan
    eos_config:
      src: customer_vxlan.j2
      
  - name: Configure Customer BGP
    eos_config:
      src: customer_bgp.j2