- hosts: leafs
  connection: local
  gather_facts: no

  tasks:
  - name: Debug rendered template
    debug:
    msg: "{{ lookup('template', 'templates/customer.j2') }}"
  
  - name: Configure Customer
    eos_config:
      src: customer.j2